### ISSUE TITLE
Could not read from remote repository (git.melting-media.com)

### ISSUE THREAD

**Issue by pixelchutes** [meltingmedia/MODX-Shell#10]
Cannot install on new system:

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

**Comment by rtripault** [comment]
I believe this today's push, no more dependencies should be pulled from my private repositories, so closing.
Please, feel free to comment/reopen if needed.
Thanks
