### ISSUE TITLE
system:log:listen error (protected property)

### ISSUE THREAD

**Issue by pixelchutes** [meltingmedia/MODX-Shell#12]
Running `modx system:log:listen` does not appear to work, errors with the following:

> PHP Fatal error:  Cannot access protected property MODX\Shell\Command\System\Log\Listen::$output in src/Command/System/Log/Listen.php on line 31

**Comment by rtripault** [comment]
Should be fixed with 8c16dc2ea2c00e20cb5dc5d1e6e9f7c33f6dd77a
Feel free to comment/reopen if needed.
Thanks
