### ISSUE TITLE
[PHP 5.3 Errors] Parse error:  syntax error, unexpected ')'

### ISSUE THREAD

**Issue by pixelchutes** [meltingmedia/MODX-Shell#7]
I just completed the first three installation steps. I received the following warning:
`Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.` which I resolved via `composer update`.

However, when simply running `modx` the following errors are given:

```
PHP Parse error:  syntax error, unexpected ')', expecting '(' in src/Command/BaseCmd.php on line 395

Parse error: syntax error, unexpected ')', expecting '(' in src/Command/BaseCmd.php on line 395
```

**NOTE:** _PHP 5.3.29 (cli) / CentOS 5.5_ ...I am not experiencing the issue in OS X 10.10.2 / PHP 5.5.14 (cli).

**Comment by pixelchutes** [comment]
I am getting a similar error calling `user:list`

```
PHP Fatal error:  Call to a member function getVersionData() on a non-object in src/Command/User/GetList.php on line 22
```

and the following in many of the other commands:

```
PHP Fatal error:  Call to a member function runProcessor() on a non-object in src/Command/ProcessorCmd.php on line 71
```

**Comment by rtripault** [comment]
Hopefully 0a1ddf2363e6ee92ec4263baefb95d8f0cf586d9 does the trick

**Comment by pixelchutes** [comment]
Thanks! All previously failing commands now working on 5.3

**Comment by rtripault** [comment]
Thanks to you! So closing this one
