### ISSUE TITLE
Missing processor limit for 2.0.x instances

### ISSUE THREAD

**Issue by pixelchutes** [meltingmedia/MODX-Shell#8]
I have a test instance configured against MODX `v2.0.8`, and running `modx resource:list` output every single Resource _(over 1,300+ records)_

Is this a limitation of the processor shipped in `2.0.x`, or perhaps a MODX-Shell compatibility bug?

**Comment by pixelchutes** [comment]
Seems this may impact other processors as well, not just `resource:list`... for example `modx s:a:l` _(system:actions:list)_

**Comment by rtripault** [comment]
Just as a note : 

https://github.com/modxcms/revolution/blob/v2.0.8-pl/core/model/modx/processors/resource/getlist.php#L18 seems to be the source

**Comment by rtripault** [comment]
2b3a415d should take care of that, so closing (feel free to comment/reopen if needed, thanks!)
