### ISSUE TITLE
Revo version: Unknown (Inconsistent)

### ISSUE THREAD

**Issue by pixelchutes** [meltingmedia/MODX-Shell#9]
I am somewhat confused, not sure if this is an actual issue, a misconfiguration on my end, or simply something not supported.

Basically, I have a few MODX Advanced installs with `/core/` located in an alternate directory _(below web root.)_ When these instances are added to the MODX-Shell configuration list, the Revo version states `Unknown` when running `modx config:list`...**However**, when I'm working _within_ the web root for said MODX instances, the version returns as expected (`2.3.3-pl` in this case.)

What I don't understand is why the version number is only returned when running MODX-Shell commands inside of the instance's base_path for MODX advanced install with non-standard `core` location. For all of my MODX `git` installs, the Revo version returns as expected regardless of your current working directory.

In case it's relevant, this is using PHP 5.3.29.

**Comment by pixelchutes** [comment]
Interesting... it seems the installs configured showing the version without issue were all instances configured on an _earlier_ version of MODX-Shell. Only those recently added have this issue.

After reviewing `~/.modx/config.ini`, it seems the problem is a missing `core_path` entry for all the newly configured sites exhibiting the Revo version: Unknown issue.

**Comment by rtripault** [comment]
Indeed, `core_path` entry was added recently, and is required for Shell to list Revo version (in order to grab `{core_path}/docs/version.php` file.

You could either remove/re-add your previous entries, or edit them, so that `core_path` in the ini file would be updated.

When listing instances, `core/docs/...` file is used, when "on" an instance, `modX::getVersionData` is (was ?) used, hence why you get the result.

Hope that makes sense

**Comment by pixelchutes** [comment]
It's the other way around though... `core_path` is **missing** from all **new** entries added.

Those added a few days ago (older MODX-Shell version), do not exhibit this problem, and `core_path` exists for those config instances only.

**Comment by rtripault** [comment]
Ah sorry, misunderstood.

Could you please let me know if baaa3fdeb74ee412e05c238925b6c36e690ace5a took care of that ?
Thanks

**Comment by pixelchutes** [comment]
All good! After remove/re-add, `config.ini` looks good now.
